spring:
    data:
        mongodb:
            uri: mongodb://localhost:27017/ob-consent-core?minPoolSize=0&maxPoolSize=3
    cloud:
        stream:
            kafka:
                binder:
                    replicationFactor: 1
                    auto-create-topics: true
                    brokers: localhost:9093
            bindings:
                consentEventListener-in-0:
                    destination: consent_events
                    group: consent-core
        function:
            definition: consentEventListener

management:
    health:
        diskspace:
            enabled: false
    endpoint:
        health:
            show-details: always
    endpoints:
        web:
            base-path: "/"
            exposure:
                include: prometheus, health
            path-mapping:
                prometheus: metrics