version: '3.7'

services:
    prometheus:
        container_name: prometheus
        image: prom/prometheus
        volumes:
            - ./prometheus.yml:/etc/prometheus/prometheus.yml
        command:
            - --config.file=/etc/prometheus/prometheus.yml
        ports:
            - 9090:9090
        networks:
            - host
    grafana:
        image: grafana/grafana
        depends_on:
            - prometheus
        ports:
            - 3000:3000
        environment:
            - GF_SECURITY_ADMIN_PASSWORD=local
            - GF_USERS_ALLOW_SIGN_UP=false
        networks:
            - host
        restart: always
volumes:
    prometheus:
    grafana:

networks:
    bubble:
        external: true
    host: